### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by chrisvidal** [rstacruz/mocha-clean#10]
I still able able to see the tracelog left by mocha or chai or chakram.

my config is:
test/mocha.opts with

``` bash
--timeout 10000
--require mocha-clean
```

test/users/my_test.js

than i run the tests

``` bash
mocha test/users
```

or like this 

``` bash
mocha test/users --require mocha-clean
```

and still see tracelog like

``` bash
AssertionError: expected header content-type with value text/html; charset=UTF-8 to match regex /json/
      at test/folders/authenticated_user_folders_assertions.js:91:42
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by wclr** [comment]
it seem not to work at all
